### ISSUE TITLE
Pick (draft) color scheme

### ISSUE THREAD

**Issue by leesoohang** [leesoohang/hotel-horizon#10]

**Comment by Msalarzon** [comment]
**_Description:_**
This update refines the color scheme used in the project for a more harmonious and visually appealing design. The chosen color combination is carefully selected to convey specific emotions and enhance the overall user experience.

**_![Color Scheme](https://github.com/leesoohang/project1/assets/148258577/f42c9604-d97b-4632-aaa5-59e9e4eb52ca)_**

- **Orange Gradient** for Buttons: The gradient transition from golden yellow (#FFD700) to dark orange (#dc4927) brings warmth and excitement, ensuring attention-grabbing and energetic button styles.

- **Green Gradient** for Example Buttons: The transition from medium green (#409257) to dark green (#0c1a10) in example buttons evokes feelings of nature, freshness, and tranquility while maintaining visual appeal.

- **Light Beige** Background for Information Boxes: The light beige (#e7e5cd) background in information boxes offers a clean and calm backdrop, enhancing readability and providing an elegant touch.

Dark Gray Background for Footer: The dark gray (#333) footer background is neutral and versatile, serving as a solid base that complements the overall color scheme.

**Comment by Msalarzon** [comment]
- Chose a simple gradient color that mirrors the website's title, neutralized all components and background to white as suggested for a more comfortable visual experience, and employed a subtle blue shade to gently highlight selected buttons.
