### ISSUE TITLE
Design modal scenarios

### ISSUE THREAD

**Issue by leesoohang** [leesoohang/hotel-horizon#2]

**Comment by Msalarzon** [comment]
A modal button was implemented within the code and temporarily placed in a corner, to be replicated or positioned as required in the future. 

Potential uses can include:
- Advanced Search Options
- Hotel Details
- Login/Signup Form
- Booking Confirmation
- Special Offers or Promotions
- Feedback or Reviews. 

![Modal](https://github.com/leesoohang/project1/assets/148258577/1c16b7a8-56a9-4d33-b7ef-88def1372951)

Any further ideas or suggestions always welcomed! :)
